# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-05 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0007_auto_20180202_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UID'),
        ),
    ]
